/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        if (args.length >= 3) {
            String inputFilePath = args[0];
            String outputFilePath = args[1];
            String transformation = args[2];

            BitMap bitmap = new BitMap(inputFilePath);

            if (transformation.equals("gray")) {
                bitmap.convertImageToGray();
            } else if (transformation.equals("invert")) {
                bitmap.invertColors();
            } else if (transformation.equals("rotate")) {
                bitmap.rotate();
            } else {
                System.out.println("Unknown transformation: " + transformation);
                System.out.println("Supported transformations: gray, invert, rotate");
                return;
            }

            bitmap.write(outputFilePath);
        } else {
            System.out.println("Usage: java App input_image.bmp output_image.bmp transformation");
            System.out.println("Supported transformations: gray, invert, rotate");
        }
    }

}